---
title: "EDA Data and Orig runs"
author: "Felix Boehm"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: yes
    toc_float: yes
    smooth_scroll: yes
    fig_width: 15
  pdf_document:
    toc: yes
  word_document:
    toc: yes
editor_options:
  markdown:
    wrap: sentence
---

```{=html}
<style type="text/css">
.main-container {
  max-width: 1800px !important;
  margin: auto;
}
</style>
```
```{r setup, include=FALSE}
knitr::opts_chunk$set(
  error = F,
	message = FALSE,
	warning = FALSE,
	include = T,
	echo = F,
	fig.width = 15,
  fig.height = 7,
	options(mc_doScale_quiet=TRUE),
  results = 'asis'
)
library(knitr)
library(gtsummary)
library(sjPlot)
library(sjmisc)
library(sjlabelled)
library(ggplot2)
library(topGO)
library(zoo)
library(binr)
library(dplyr)
library(vioplot)
setwd("C:/Users/iXilef/OneDrive/Master/initial")
```

```{r}
load("./data/misc.RData")
load("./data/annotations.RData")
load("./data/orig_results.RData")
```

# Histograms of GO Annotations

```{r}
par(mfrow=c(1,3))
hist(log10(sapply(annotations$orig, length)), nclass=100, main="A) Histogramm of Original Data \n Number of GO terms annotated to transcripts",
     xaxt="n", las=3, xlab="Number of GO Terms per Transcript", ylab="Frequency of Transcripts", ylim=c(0,1200))
axis(side=1, at=log10(c(1,5,10,25,50,100,250,500,1000)), labels=c(1,5,10,25,50,100,250,500,1000), las=3)
abline(v=median(log10(sapply(annotations$orig, length))), col="purple")
abline(v=mean(log10(sapply(annotations$orig, length))), col="red")

hist(log10(sapply(annotations$rat, length)), nclass=100, main="B) Histogramm of Rat Data \n Number of GO terms annotated to transcripts",
     xaxt="n", las=3, xlab="Number of GO Terms per Transcript", ylab="Frequency of Transcripts", ylim=c(0,1200))
axis(side=1, at=log10(c(1,5,10,25,50,100,250,500,1000)), labels=c(1,5,10,25,50,100,250,500,1000), las=3)
abline(v=median(log10(sapply(annotations$rat, length))), col="purple")
abline(v=mean(log10(sapply(annotations$rat, length))), col="red")


hist(log10(sapply(annotations$human, length)), nclass=100, main="C) Histogramm of Human Data \n Number of GO terms annotated to transcripts",
     xaxt="n", las=3, xlab="Number of GO Terms per Transcript", ylab="Frequency of Transcripts", ylim=c(0,1300))
axis(side=1, at=log10(c(1,5,10,25,50,100,250,500,1000)), labels=c(1,5,10,25,50,100,250,500,1000), las=3)
abline(v=median(log10(sapply(annotations$human, length))), col="purple")
abline(v=mean(log10(sapply(annotations$human, length))), col="red")
```


```{r}
par(mfrow=c(1,3))
hist(log10(sapply(inverseList(annotations$orig), length)), nclass=100, main="A) Histogramm of Original Data \n Number of transcripts annotated to GO terms",
     xaxt="n", las=3, xlab="Number of Transcripts per GO Term", ylab="Frequency of Transcripts", ylim=c(0,2200))
axis(side=1, at=log10(c(1,5,10,25,50,100,250,500,1000,2500,5000,10000)), labels=c(1,5,10,25,50,100,250,500,1000,2500,5000,10000), las=3)
abline(v=median(log10(sapply(inverseList(annotations$orig), length))), col="purple")
abline(v=mean(log10(sapply(inverseList(annotations$orig), length))), col="red")

hist(log10(sapply(inverseList(annotations$rat), length)), nclass=100, main="B) Histogramm of Rat Data \nNumber of transcripts annotated to GO terms",
     xaxt="n", las=3, xlab="Number of Transcripts per GO Term", ylab="Frequency of Transcripts", ylim=c(0,2200))
axis(side=1, at=log10(c(1,5,10,25,50,100,250,500,1000,2500,5000,10000)), labels=c(1,5,10,25,50,100,250,500,1000,2500,5000,10000), las=3)
abline(v=median(log10(sapply(inverseList(annotations$rat), length))), col="purple")
abline(v=mean(log10(sapply(inverseList(annotations$rat), length))), col="red")


hist(log10(sapply(inverseList(annotations$human), length)), nclass=100, main="C) Histogramm of Human Data \n Number of transcripts annotated to GO terms",
     xaxt="n", las=3, xlab="Number of Transcripts per GO Term", ylab="Frequency of Transcripts", ylim=c(0,2200))
axis(side=1, at=log10(c(1,5,10,25,50,100,250,500,1000,2500,5000,10000)), labels=c(1,5,10,25,50,100,250,500,1000,2500,5000,10000), las=3)
abline(v=median(log10(sapply(inverseList(annotations$human), length))), col="purple")
abline(v=mean(log10(sapply(inverseList(annotations$human), length))), col="red")
```

```{r}
```


```{r}
kable(cbind(c("N", "Original", "Rat", "Human"),
      rbind(c(c(1,5,10,25,50,100,250,500,1000)),
            sapply(c(1,5,10,25,50,100,250,500,1000), function(x) length(which(sapply(annotations$orig, length) >= x))),
      sapply(c(1,5,10,25,50,100,250,500,1000), function(x) length(which(sapply(annotations$rat, length) >= x))),
      sapply(c(1,5,10,25,50,100,250,500,1000), function(x) length(which(sapply(annotations$human, length) >= x)))),
      Median=c("",round(10^c(median(log10(sapply(annotations$orig, length))), median(log10(sapply(annotations$rat, length))), median(log10(sapply(annotations$human, length)))), digits=0)),
      Mean=c("",round(10^c(mean(log10(sapply(annotations$orig, length))), mean(log10(sapply(annotations$rat, length))), mean(log10(sapply(annotations$human, length)))), digits=0))), caption="Number of Transcripts which have N or higher GO Terms annotated to it")
```


```{r}
kable(cbind(c("N", "Original", "Rat", "Human"),
      rbind(c(c(1,5,10,25,50,100,250,500,1000,2500,5000,10000)),
            sapply(c(1,5,10,25,50,100,250,500,1000,2500,5000,10000), function(x) length(which(sapply(inverseList(annotations$orig) , length) >= x))),
      sapply(c(1,5,10,25,50,100,250,500,1000,2500,5000,10000), function(x) length(which(sapply(inverseList(annotations$rat) , length) >= x))),
      sapply(c(1,5,10,25,50,100,250,500,1000,2500,5000,10000), function(x) length(which(sapply(inverseList(annotations$human) , length) >= x)))),
      Median=c("",round(10^c(median(log10(sapply(inverseList(annotations$orig), length))), median(log10(sapply(inverseList(annotations$rat), length))), median(log10(sapply(inverseList(annotations$human), length)))), digits=0)),
      Mean=c("",round(10^c(mean(log10(sapply(inverseList(annotations$orig), length))), mean(log10(sapply(inverseList(annotations$rat), length))), mean(log10(sapply(inverseList(annotations$human), length)))), digits=0))), caption="Number of GO terms which have N or higher Transcripts annotated to it")
```


# Original Data

```{r}
par(mfrow=c(1,2))



plot(results_orig$seq_info$FC.sep, log10(results_orig$seq_info$nmember_real), main="A) Number of GO terms annotated to one transcript 
     vs. the respective log2FC", ylab="Number of annotated GO terms per transcripts", xlab="log2 Fold Change", yaxt="n")
abline(h=log10(c(1,2,5,10,25,50,100,200,500,1250,3500)), v=seq(-6,6,1), col=alpha("grey", 0.5))
abline(v=mean(results_orig$seq_info$FC.sep), col="red")
abline(v=median(results_orig$seq_info$FC.sep), col="purple")
axis(side = 2, at=log10(c(1,2,5,10,25,50,100,200,500,1250,3500)), labels=c(c(1,2,5,10,25,50,100,200,500,1250,3500)),las=1)

plot(results_orig$go$medianFC, log10(results_orig$go$ntrans_real), main="B) Median log2FC in each GO term vs. \n the number of annotated transcripts", ylab="log(Number) of annotated transcripts in the dataset", xlab="Mean log2FC of the transcripts in one GO term", yaxt="n",las=1, xlim=c(-1,2))
abline(h=log10(c(1,2,5,10,25,50,100,200,500,1250,3500)), v=seq(-6,6,.5), col=alpha("grey", 0.5))
abline(v=mean(results_orig$go$medianFC, na.rm=T), col="red")
abline(v=median(results_orig$go$medianFC, na.rm=T), col="purple")
axis(side = 2, at=log10(c(1,2,5,10,25,50,100,200,500,1250,3500)), labels=c(c(1,2,5,10,25,50,100,200,500,1250,3500)),las=1)


```


```{r}
# get cum median of fc by membership
fc_N <- as.data.frame(cbind(0:max(results_orig$seq_info$nmember_real), sapply(0:max(results_orig$seq_info$nmember_real),
                                                    function(x) median(results_orig$seq_info$FC.sep[which(results_orig$seq_info$nmember_real > x)])))); colnames(fc_N) <- c("N", "medianFC")

# get binned median of fc by membership
results_orig$seq_info$bins <- ntile(results_orig$seq_info$nmember_real,20)

results_orig$seq_info %>% group_by(bins) %>% summarise(medianfc=median(FC.sep), median = round(mean(nmember_real)), digits=2) -> fc_Median

results_orig$seq_info$bins <- ntile(results_orig$seq_info$nmember_real,100)
results_orig$seq_info %>% group_by(bins) %>% summarise(medianfc=median(FC.sep), median = round(mean(nmember_real)), digits=2) -> fc_MED

results_orig$seq_info$bins <- ntile(results_orig$seq_info$nmember_real,200)
results_orig$seq_info %>% group_by(bins) %>% summarise(medianfc=median(FC.sep), median = round(mean(nmember_real)), digits=2) -> fc_MED2

par(mfrow=c(1,2))





colfunc <- colorRampPalette(c("grey", "orange"))
plot(density(results_orig$seq_info$FC.sep,na.rm=T),lwd=3, main="A) Distribution of log2 Fold change values by \n how many membership in GO terms it has")
abline(v=0)
# Which transcripts show up more than N times:
index=1
for (N in seq(0,300,50))
{
lines(density(results_orig$seq_info$FC.sep[which(results_orig$seq_info$nmember_real>N)] ,na.rm=T),col=colfunc(7)[index]) # selected transcripts plotted
index <- index+1
}
legend("topright", legend=c("> 0", "> 50", "> 100", "> 150", "> 200", "> 250", "> 300"), col=c("black", colfunc(7)), title = "Number \n of memberships", lty = 1)

plot(fc_N$N, fc_N$medianFC, main="B) Median log2FC over the number of annotated GO terms", ylab="Median log2FC", xlab="Number of annotated GO terms", type="l", ylim=c(-.5,1.2), col="red")
lines(fc_MED2$median, fc_MED2$medianfc, col="purple")
lines(fc_MED$median, fc_MED$medianfc, col="black")
lines(fc_Median$median, fc_Median$medianfc, col="blue")
abline(h=0)
legend("bottomright", legend=c("Cumulative Median", "Sliding Window Median Bins = 20", "Sliding Window Median Bins = 100", "Sliding Window Median Bins = 200"), col=c("red", "blue", "black", "purple"), lty = 1)

kable(rbind(round(sapply(seq(0,300,50), function(x) mean(results_orig$seq_info$FC.sep[which(results_orig$seq_info$nmember_real>x)],na.rm=T)), digits=3),
round(sapply(seq(0,300,50), function(x) median(results_orig$seq_info$FC.sep[which(results_orig$seq_info$nmember_real>x)],na.rm=T)), digits=3)))



```


```{r}

```


# Bias modeling


## Model for Bias

```{r}
par(mfrow=c(1,2))
misc$trans$nmemberlog10 <- log10(misc$trans$nmember_real)
real_lm <- lm(FC.sep~nmemberlog10, data=misc$trans)


tab_model(real_lm, dv.labels=c("log2FC"))

# plot(real_lm, which=2, main="log2FC QQPlot")

plot(misc$trans$FC.sep~log10(misc$trans$nmember_real), main="A) log10(Number of GO Terms) over log2FC per Transcript \n red line = linear regression", ylab="log2FC", xlab="log10 of Number of GO terms per transcript")
abline(real_lm, col="red")


colfunc <- colorRampPalette(c("grey", "orange"))
index=1
x <- seq(-2,4,0.1)
plot(x, y=0*x, type="l", lwd=2, main="B) Mean functions used for the bias modelling \n in the random sampling iterations", xlab="Number of GO terms per transcript", ylab="log2 Fold Change", xlim=c(0,4), xaxt="n")
axis(side=1, at=log10(c(1,3,5,10,17,25,50,100,250,500,1000,2500,5000,10000)), labels=c(1,3,5,10,17,25,50,100,250,500,1000,2500,5000,10000), las=3)
for(i in seq(0,0.35, 0.05)){
  intercept <- 1.23221*i
  lines(x, y=i*x-intercept, col=colfunc(8)[index], lwd=2)
  index <- index+1
  print(intercept)
}
abline(v= 0, h=0)
abline(v=1.23221, col="blue", lwd=2)
abline(real_lm, col="red", lwd=2)
legend("bottomright", legend=c(seq(0,0.35, 0.05), "Original y=0", "Original LM"), title="Slopes", col = c(colfunc(8), "blue", "red"), lty = 1, lwd=2)
```


```{r}


kable(cbind(c("Data", "Original", "Rat", "Human"), rbind(c("Below 17", "Below 17 & Above 10", "Above 17"),
                                                   c(length(which(sapply(annotations$orig, length) < 17)),
                                                     length(which(sapply(annotations$orig, length) < 17 & sapply(annotations$orig, length) >= 10)), 
                                                     length(which(sapply(annotations$orig, length) > 17))),
                                                   c(length(which(sapply(annotations$rat, length) < 17)),
                                                     length(which(sapply(annotations$rat, length) < 17 & sapply(annotations$rat, length) >= 10)),
                                                     length(which(sapply(annotations$rat, length) > 17))),
                                                   c(length(which(sapply(annotations$human, length) < 17)),
                                                     length(which(sapply(annotations$human, length) < 17 & sapply(annotations$human, length) >= 10)),
                                                     length(which(sapply(annotations$human, length) > 17))))),caption="Number of Transcripts with Numbers of GO terms associated")
```

# Original runs

```{r}
sig_GO <- c("classic"=length(which(results_orig$ks$classic < 0.05)),
            "classic fdr"=length(which(p.adjust(results_orig$ks$classic, method="fdr") < 0.05)),
            "elim"=length(which(results_orig$ks$elim < 0.05)), 
            "weight"=length(which(results_orig$ks$weight01 < 0.05)),
            "mwu"=length(which(results_orig$mwu$pval < 0.05)),
            "mwu fdr"=length(which(p.adjust(results_orig$mwu$pval, method="fdr") < 0.05)))


sig_GO_size <-as.data.frame(rbind(cbind(N=results_orig$ks$Annotated[which(results_orig$ks$classic < 0.05)], method="classic"),
            cbind(N=results_orig$ks$Annotated[which(p.adjust(results_orig$ks$classic, method="fdr") < 0.05)], method="classic fdr"),
            cbind(N=results_orig$ks$Annotated[which(results_orig$ks$elim < 0.05)], method="elim"), 
            cbind(N=results_orig$ks$Annotated[which(results_orig$ks$weight01 < 0.05)], method="weight"),
            cbind(N=results_orig$mwu$nseqs[which(results_orig$mwu$pval < 0.05)], method="mwu"),
            cbind(N=results_orig$mwu$nseqs[which(p.adjust(results_orig$mwu$pval, method="fdr") < 0.05)], method="mwu fdr")))

sig_GO_size$N <- as.numeric(sig_GO_size$N)

par(mfrow=c(1,2))
barplot(sig_GO, col=colfunc(6), ylim=c(0,1100), main="A) Number of significant GO Terms")
legend("topleft", title="", legend = paste(c("Classic =", "Classic FDR =", "ELIM =", "Weight =", "MWU =", "MWU FDR = "), sig_GO), horiz=F, cex=.8, box.lty = 0, fill=colfunc(6), bg="transparent")

vioplot(log10(sig_GO_size$N)~sig_GO_size$method, yaxt="n", col=colfunc(6), main="B) Size of significant GO terms per method", ylab="Size of GO term", xlab="Method")
stripchart(log10(sig_GO_size$N)~sig_GO_size$method, yaxt="n", add=T, vertical=T, method="jitter", pch=19, col = alpha("blue", .1))

axis(side=2, at=log10(c(1,3,5,10,15,25,50,100,250,500,1000,2500,5000,10000)), labels=c(1,3,5,10,15,25,50,100,250,500,1000,2500,5000,10000), las=1)
     
points(log10(sig_GO_size$N)~sig_GO_size$method)

# kable(sig_GO)
```


```{r}
par(mfrow=c(1,4))
colfunc <- colorRampPalette(c("blue","black","grey","orange"))
# seq_info <- results_normal$original$seq_info

plot(results_orig$seq_info$FC.sep, results_orig$seq_info$nmember_mwu, col="black", ylab="Times Transcript is a member of significant GO term",
     xlab="log2 Fold change", main="A) MWU", ylim=c(0,250))
abline(v=median(results_orig$seq_info$FC.sep[which(results_orig$seq_info$nmember_mwu > 20)]), col=colfunc(4)[1])
plot(results_orig$seq_info$FC.sep, results_orig$seq_info$nmember_classic_sig, col="blue", ylab="Times Transcript is a member of significant GO term",
     xlab="log2 Fold change", main="B)  Classic", ylim=c(0,250))
abline(v=median(results_orig$seq_info$FC.sep[which(results_orig$seq_info$nmember_classic_sig > 20)]), col="blue")
plot(results_orig$seq_info$FC.sep, results_orig$seq_info$nmember_elim_sig, col="orange", ylab="Times Transcript is a member of significant GO term",
     xlab="log2 Fold change", main="C)  Elim", ylim=c(0,250))
abline(v=median(results_orig$seq_info$FC.sep[which(results_orig$seq_info$nmember_elim_sig > 20)]), col="orange")
plot(results_orig$seq_info$FC.sep, results_orig$seq_info$nmember_weight_sig, col="grey", ylab="Times Transcript is a member of significant GO term",
     xlab="log2 Fold change", main="D) Weight", ylim=c(0,250))
abline(v=median(results_orig$seq_info$FC.sep[which(results_orig$seq_info$nmember_weight_sig > 20)]), col="green")

```

```{r}
par(mfrow=c(1,3))

plot(results_orig$seq_info$FC.sep, results_orig$seq_info$nmember_mwu, col="black", ylab="Times Transcript is a member of significant GO term",
     xlab="log2 Fold change", main="A)  MWU FDR", ylim=c(0,250))
abline(v=median(results_orig$seq_info$FC.sep[which(results_orig$seq_info$nmember_mwu_fdr > 20)]), col="black")
plot(results_orig$seq_info$FC.sep, results_orig$seq_info$nmember_classic_sig_fdr, col="blue", ylab="Times Transcript is a member of significant GO term",
     xlab="log2 Fold change", main="B)  Classic FDR", ylim=c(0,250))
abline(v=median(results_orig$seq_info$FC.sep[which(results_orig$seq_info$nmember_classic_sig_fdr > 20)]), col="blue")



plot(results_orig$medi_lines$N, results_orig$medi_lines$median_mwu, col=colfunc(6)[1], type="l", ylim=c(0, 3), main="C) Cumulative Median of log2 Fold Change \n by transcripts being above a certain number of GO terms", ylab="log2 Fold change", xlab="Number of annotated GO terms")


lines(results_orig$medi_lines$N, results_orig$medi_lines$median_mwu_fdr, col=colfunc(6)[2])

lines(results_orig$medi_lines$N, results_orig$medi_lines$median_classic, col=colfunc(6)[3])

lines(results_orig$medi_lines$N, results_orig$medi_lines$median_classic_fdr, col=colfunc(6)[4])

lines(results_orig$medi_lines$N, results_orig$medi_lines$median_elim, col=colfunc(6)[5])

lines(results_orig$medi_lines$N, results_orig$medi_lines$median_weight01, col=colfunc(6)[6])

legend("topright", legend=c("MWU", "MWU FDR", "Classic", "Classic FDR", "Elim", "Weight"), col=colfunc(6), lty = 1)

```

